export const GET_PRODUCT_PENDING = "GET_PRODUCT-PENDING"
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT-SUCCESS"
export const GET_PRODUCT_ERROR = "GET_PRODUCT-ERROR"

export const POST_PRODUCT_PENDING = "POST_PRODUCT-PENDING"
export const POST_PRODUCT_SUCCESS = "POST_PRODUCT-SUCCESS"
export const POST_PRODUCT_ERROR = "POST_PRODUCT-ERROR"

export const DELETE_PRODUCT_PENDING = "DELETE_PRODUCT-PENDING"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT-SUCCESS"
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT-ERROR"

export const UPDATE_PRODUCT_PENDING = "UPDATE_PRODUCT-PENDING"
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT-SUCCESS"
export const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT-ERROR"


